shop/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Admin
Route::group(['middleware'=>'admin','namespace'=>'Admin'],function (){
    Route::get('/admin/products', 'AdminController@products')->name('products.show');
    Route::get('/admin/orders', 'AdminController@orders')->name('admin.orders');
    Route::get('/admin/customers', 'AdminController@customers')->name('admin.customers');
    Route::get('/admin/sellers', 'AdminController@sellers')->name('admin.sellers');

    Route::resource('/admin', 'AdminController');
    Route::delete('/admin/{id}/{from}', 'AdminController@destroy')->name('admin.destroy');

});
// Seller
Route::group(['middleware'=>'seller','namespace'=>'Seller'],function (){
    Route::get('/seller', 'SellerController@index')->name('seller');
    Route::resource('/product','ProductController');
    Route::get('product/images/{id}','ProductController@image')->name('product.show');
    Route::get('product/{id}/images','ProductController@image')->name('product.show');
    Route::delete('product/{id}/images/{image}','ProductController@delete')->name('img.destroy');
    Route::get('product/{id}/images/{image}','ProductController@head')->name('make_header');
    Route::get('seller/order','SellerController@myOrders')->name('myOrders');
    Route::delete('seller/order/{delete}','SellerController@destroy')->name('myorder.delete');
    Route::put('seller/order','SellerController@confirm')->name('order.confirm');

});
//Customer
Route::group(['middleware'=>'customer','namespace'=>'Customer','prefix'=>'customer'],function (){
    Route::get('/', 'CustomerController@index')->name('customer');
    Route::resource('/order', 'OrderController');
});

shop/app/Http/Controllers/Customer/CustomerController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
    public function index()
    {
        return view('customer.index');
    }
}

shop/app/Http/Controllers/Customer/OrderController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        return view('customer.orders');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      Order::create([
          'count'=>$request->count,
          'product_id'=>$request->id,
          'user_id'=>auth()->user()->id,
          'confirmed'=>2,
      ]);
      return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

shop/resources/views/customer/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @foreach(App\Models\Product::where('confirmed',1)->get() as $prod )
                <div class="col-3">
                    <div class="card" >
                        <img src="{{asset('uploads/'.$prod->img)}}" class="card-img-top" alt="...">
                        <div class="card-body ">
                            <h5 class="card-title">{{$prod->name}}</h5>
                            <p class="card-text">{{$prod->description}}</p>
                            <span class="card-text">{{$prod->cost}} <b>amd</b>  </span>
                            <div class="text-center">
                                <a href="" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" data-curent="{{$prod->id}}"> Buy now</a>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">{{$prod->name}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>{{$prod->cost}} <b>amd</b></p>
                                <form action="{{route('order.store',['id'=>$prod->id])}}" method="POST">
                                    @csrf
                                    <div class="form-group row">
                                        <label for="text" class="col-md-4 col-form-label text-md-right">Count</label>
                                        <div class="col-md-6">
                                            <input type="number" class="form-control" name="count" min ='1' max ='10' value = '1'/>
                                            <input type="hidden" name="product_id" value="{{ $prod->id }}" />

                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Buy</button>
                                </form>

                            </div>

                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

shop/resources/views/customer/orders.blade.php
@extends('layouts.app')
<style>
    img.img-fluid {
        display: inline-block;
        height:60px ;
        width:auto ;
    }
</style>
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Cost</th>
                        <th>Count</th>
                        <th>All Price</th>
                        <th>Image</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach(App\Models\Order::where('user_id',auth()->user()->id)->get() as $item )
                        <tr>
                            <td>{{ $item->product->name}} </td>
                            <td>{{ $item->product->description }}</td>
                            <td>{{ $item->product->cost }}</td>
                            <td>{{ $item->count }}</td>
                            <td>{{ $item->count * $item->product->cost }}</td>
                            <td><img src="{{asset('uploads\thumb\\'.$item->product->img )}}" class="img-fluid"  alt=""/></td>
                            <td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection