shop/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Admin
Route::group(['middleware'=>'admin','namespace'=>'Admin'],function (){
    Route::get('/admin/products', 'AdminController@products')->name('products.show');
    Route::get('/admin/orders', 'AdminController@orders')->name('admin.orders');
    Route::get('/admin/customers', 'AdminController@customers')->name('admin.customers');
    Route::get('/admin/sellers', 'AdminController@sellers')->name('admin.sellers');

    Route::resource('/admin', 'AdminController');
    Route::delete('/admin/{id}/{from}', 'AdminController@destroy')->name('admin.destroy');

});
// Seller
Route::group(['middleware'=>'seller','namespace'=>'Seller'],function (){
    Route::get('/seller', 'SellerController@index')->name('seller');
    Route::resource('/product','ProductController');
    Route::get('product/images/{id}','ProductController@image')->name('product.show');
    Route::get('product/{id}/images','ProductController@image')->name('product.show');
    Route::delete('product/{id}/images/{image}','ProductController@delete')->name('img.destroy');
    Route::get('product/{id}/images/{image}','ProductController@head')->name('make_header');
    Route::get('seller/order','SellerController@myOrders')->name('myOrders');
    Route::delete('seller/order/{delete}','SellerController@destroy')->name('myorder.delete');
    Route::put('seller/order','SellerController@confirm')->name('order.confirm');

});
//Customer
Route::group(['middleware'=>'customer','namespace'=>'Customer','prefix'=>'customer'],function (){
    Route::get('/', 'CustomerController@index')->name('customer');
    Route::resource('/order', 'OrderController');
});

shop/resources/views/admin/customers.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(App\Models\User::where('role','customer')->count()>0)
            <div class="row justify-content-center">
                <div class="col-xl-8 ">
                    <h3 class="text-center">Customers</h3>

                    <table class="table mt-3 jquery_table"  >
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Mail</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(App\Models\User::where('role','customer')->get() as $user)
                            <tr data-id="{{$user->id}}" >
                                <td>{{ $user->name}} </td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->role }}</td>
                                <td>
                                    <a href="{{route('admin.destroy',['id'=>$user->id ,'from'=>'user'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>

                    </table>

                </div>
                @endif




            </div>
    </div>

@endsection

shop/resources/views/admin/index.blade.php
@extends('layouts.app')
{{--@section('header')
@parent
@endsection--}}
@section('content')
    <div class="alert text-center alert-info">
        Welcome Admin page {{auth()->user()->name}}:
    </div>

@endsection

shop/resources/views/admin/orders.blade.php
@extends('layouts.app')

<style>
    img.img-fluid {
        display: inline-block;
        height:50px ;
        width:auto ;
    }
</style>
@section('content')
    <div class="container">

        @if(App\Models\Order::where('confirmed',0)->count()>=0)

            <div class="row justify-content-center">
                <div class="col-xl-8 ">
                    <h3 class="text-center">Confirmable Orders</h3>

                    <table class="table mt-3 jquery_table"  >
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th>Description</th>
                            <th>Cost</th>
                            <th>Image</th>
                            <th>Count</th>
                            <th>User</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach(App\Models\Order::where('confirmed',0)->get() as $item)

                            <tr data-id="{{$item->id}}" >
                                <td>{{ $item->product->name}} </td>
                                <td>{{ $item->product->description }}</td>
                                <td>{{ $item->product->cost }}</td>
                                <td>
                                    <a href="{{route('product.show',['id'=>$item->id])}}" ><img src="{{asset('uploads\thumb\\'.$item->img )}}" class="img-fluid"  alt=""/>
                                    </a></td>
                                <td>{{ $item->count }}</td>
                                <td>{{ $item->user->name }}</td>
                                <td>
                                    <form method ='POST' action="{{route('admin.update',['id'=>$item->id])}}" class="d-inline-block" >
                                        <input type="hidden" name="type" value="order" />
                                        @method('PUT')
                                        @csrf
                                        <button class="btn btn-primary" type ='submit'> Confirm </button> </form></td>
                                <td>
                                    <a href="{{route('admin.destroy',['id'=>$item->id ,'from'=>'order'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>

                    </table>

                </div>
                @endif
                <div class="col-xl-8 mt-5">
                    <h3 class="text-center"> Orders</h3>

                    <table class="table mt-3 jquery_table">
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th>Description</th>
                            <th>Cost</th>
                            <th>Image</th>
                            <th>Count</th>
                            <th>User</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(App\Models\Order::all() as $item)


                            <tr data-id="{{$item->id}}" >
                                <td>{{ $item->product->name}} </td>
                                <td>{{ $item->product->description }}</td>
                                <td>{{ $item->product->cost }}</td>

                                <td>
                                    <a href="{{route('product.show',['id'=>$item->id,'type'=>'order'])}}" ><img src="{{asset('uploads\thumb\\'.$item->img )}}" class="img-fluid"  alt=""/>
                                    </a></td>
                                <td>{{ $item->count }}</td>
                                <td>{{ $item->user->name }}</td>

                                <td>
                                    <a href="{{route('admin.destroy',['id'=>$item->id,'type'=>'order'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>


            </div>
    </div>

@endsection

shop/resources/views/admin/products.blade.php
@extends('layouts.app')
<style>
    img.img-fluid {
        display: inline-block;
        height:50px ;
        width:auto ;
    }
</style>
@section('content')
    <div class="container">
        @if(App\Models\Product::where('confirmed',0)->count()>0)
            <div class="row justify-content-center">
                <div class="col-xl-8 ">
                    <h3 class="text-center">Confirmable Products</h3>
                    <table class="table mt-3 jquery_table"  >
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Cost</th>
                            <th>Image</th>
                            <th>Listing</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(App\Models\Product::where('confirmed',0)->get() as $item)
                            <tr data-id="{{$item->id}}" >
                                <td>{{ $item->name}} </td>
                                <td>{{ $item->description }}</td>
                                <td>{{ $item->cost }}</td>
                                <td>
                                    <a href="{{route('product.show',['id'=>$item->id])}}" ><img src="{{asset('uploads\thumb\\'.$item->img )}}" class="img-fluid"  alt=""/>
                                    </a></td>
                                <td>
                                    <form method ='POST' action="{{route('admin.update',['id'=>$item->id])}}" class="d-inline-block" >
                                        <input type="hidden" name="type" value="product" />

                                        @method('PUT')
                                        @csrf
                                        <button class="btn btn-primary" type ='submit'> Confirm </button> </form></td>
                                <td>

                                    <a href="{{route('admin.destroy',['id'=>$item->id,'type'=>'product'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                @endif
                <div class="col-xl-8 mt-5">
                    <h3 class="text-center"> Products</h3>

                    <table class="table mt-3 jquery_table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Cost</th>
                            <th>Owner</th>
                            <th>Image</th>
                            <th>Listing</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(App\Models\Product::all() as $item)
                            <tr data-id="{{$item->id}}">
                                <td>{{ $item->name}} </td>
                                <td>{{ $item->description}}</td>
                                <td>{{ $item->cost }}</td>
                                <td>{{ $item->user->name }}</td>
                                <td><a href="{{route('product.show',['id'=>$item->id])}}" class=""><img src="{{asset('uploads\thumb\\'.$item->img )}}" class="img-fluid"  alt=""/></a></td>
                                {{--<td>

                                    <form method ='POST' action="{{route('admin.update',['id'=>$item->id])}}" class="d-inline-block" >
                                        @method('PUT')
                                        @csrf
                                        <button class="btn btn-primary" type ='submit'> Hide </button> </form></td>--}}
                                <td>
                                    <a href="{{route('admin.destroy',['id'=>$item->id,'type'=>'product'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>


            </div>
    </div>

@endsection

shop/resources/views/admin/sellers.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(App\Models\User::where('role','seller')->count()>0)
            <div class="row justify-content-center">
                <div class="col-xl-8 ">
                    <h3 class="text-center">Sellers</h3>

                    <table class="table mt-3 jquery_table"  >
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Mail</th>
                            <th>Role</th>
                            <th>Listing</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach(App\Models\User::where('role','seller')->get() as $user)
                            <tr data-id="{{$user->id}}" >
                                <td>{{ $user->name}} </td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->role }}</td>

                                <td>
                                    <a href="{{route('admin.destroy',['id'=>$user->id,'type'=>'user'])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>

                    </table>

                </div>
                @endif




            </div>
    </div>

@endsection