shop/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Admin
Route::group(['middleware'=>'admin','namespace'=>'Admin'],function (){
    Route::get('/admin/products', 'AdminController@products')->name('products.show');
    Route::get('/admin/orders', 'AdminController@orders')->name('admin.orders');
    Route::get('/admin/customers', 'AdminController@customers')->name('admin.customers');
    Route::get('/admin/sellers', 'AdminController@sellers')->name('admin.sellers');

    Route::resource('/admin', 'AdminController');
    Route::delete('/admin/{id}/{from}', 'AdminController@destroy')->name('admin.destroy');

});
// Seller
Route::group(['middleware'=>'seller','namespace'=>'Seller'],function (){
    Route::get('/seller', 'SellerController@index')->name('seller');
    Route::resource('/product','ProductController');
    Route::get('product/images/{id}','ProductController@image')->name('product.show');
    Route::get('product/{id}/images','ProductController@image')->name('product.show');
    Route::delete('product/{id}/images/{image}','ProductController@delete')->name('img.destroy');
    Route::get('product/{id}/images/{image}','ProductController@head')->name('make_header');
    Route::get('seller/order','SellerController@myOrders')->name('myOrders');
    Route::delete('seller/order/{delete}','SellerController@destroy')->name('myorder.delete');
    Route::put('seller/order','SellerController@confirm')->name('order.confirm');

});
//Customer
Route::group(['middleware'=>'customer','namespace'=>'Customer','prefix'=>'customer'],function (){
    Route::get('/', 'CustomerController@index')->name('customer');
    Route::resource('/order', 'OrderController');
});

shop/app/Http/Controllers/Seller/ProductController.php
<?php

namespace App\Http\Controllers\Seller;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Image;
use Image as Img;
use App\Models\Product;
use Illuminate\Support\Facades\File;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function head($id ,$img)
    {
        $image = Image::findorFail($img);
        $image->product->update(['img'=>$image->name]);
        return redirect()->route('product.index');
    }
    public function delete($id,$img)
    {
        $images = Image::delete_img($img);
        if($images->name == Product::find($id)->img) {
            $data =  Product::find($id);
            $data->img = 'noimage.jpg';
            $data->save();
        }
        return response()->json(array($images));

    }
    public function image($id)
    {
        $images = Product::findorFail($id)->images();

        return view('seller.images',compact('images'));
    }
    public function index()
    {
        return view('seller.product');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('seller.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
                'name'=>'required',
                'cost'=>'required|numeric',
                'description'=>'required',
                'img'=>'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]
        );
        $product = Product::create([
            'name'=>$request->name,
            'cost'=>$request->cost,
            'description'=>$request->description,
            'user_id'=>auth()->user()->id,
            'img'=>'noimage.jpg',
        ]);
        if($request->images[0]) {
            foreach ($request->images as $image) {
                $name = $image->getClientOriginalName();
                Image::create([
                    'name'=>$name,
                    'product_id'=>$product->id,
                ]);
                if(!file_exists(public_path().'\uploads\thumb\\')) {
                    File::makeDirectory(public_path().'\uploads\thumb\\',0777,true);
                }
                $fullpath = public_path().'\uploads\\'.$name;
                if(!file_exists($fullpath)) {
                    $thumbpath = public_path().'\uploads\thumb\\'.$name;
                    list($width, $height) = getimagesize($image);
                    $img = Img::make($image);
                    $img->save($fullpath ,60);
                    if($width>$height) {
                        $img->resize(300,200)->save( $thumbpath,30);
                    }
                    else {
                        $img->resize(200,300)->save( $thumbpath,30);
                    }
                }
            }
        }
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data =  Product::findorFail($id);
        return view('seller.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Product::findorFail($id);
        $data->update($request->all());
        if($request->images[0]) {
            foreach ($request->images as $image) {
                $name = $image->getClientOriginalName();
                Image::create([
                    'name' => $name,
                    'product_id' => $id,
                ]);
                if (!file_exists(public_path() . '\uploads\thumb\\')) {
                    File::makeDirectory(public_path().'\uploads\thumb\\', 0777, true);
                }
                $fullpath = public_path() . '\uploads\\' . $name;
                if (!file_exists($fullpath)) {
                    $thumbpath = public_path() . '\uploads\thumb\\' . $name;
                    list($width, $height) = getimagesize($image);
                    $img = Img::make($image);
                    $img->save($fullpath, 60);
                    if ($width > $height) {
                        $img->resize(300, 200)->save($thumbpath, 30);
                    } else {
                        $img->resize(200, 300)->save($thumbpath, 30);
                    }
                }
            }
        }
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $prod = Product::delete_product($id);
        return response()->json(array($prod));
    }
}

shop/app/Http/Controllers/Seller/SellerController.php
<?php

namespace App\Http\Controllers\Seller;

use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SellerController extends Controller
{
    public function index() {
        return view('seller.index');
    }
    public function myOrders() {
        return view('seller.orders');
    }
    public function destroy($id) {
        $data = Order::findorFail($id);
        $data->delete();
        return response()->json(array($data));
    }

    public function confirm(Request $request) {
        $order = Order::find($request->id);
        // skzbus bolor orderneri confirmed@ 2 a ete seller@ confirm a anum darnum a 0 u order@ haytnvum a admini cucakum
        if($order->confirmed == 2) {
            $order->confirmed = 0;
            $order->save();
        }
        return redirect()->back();
    }
}

shop/app/Http/Controllers/SellerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SellerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('seller.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

shop/resources/views/seller/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">

        <div class="col-md-8 ">
            <div class="card">
                <div class="card-header">Add Product</div>
                <div class="card-body">
                    <form method="POST" action="{{route('product.store')}} " enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                            <div class="col-md-6"><input id="name" type="text" name="name"  required="required" autofocus="autofocus" class="form-control"></div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-md-4 col-form-label text-md-right">Description</label>
                            <div class="col-md-6"><textarea id="password"  name="description" required="required" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-md-4 col-form-label text-md-right">Cost</label>
                            <div class="col-md-6">
                                <input type="number" class="form-control" name="cost"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-md-4 col-form-label text-md-right">Image</label>
                            <div class="col-md-6">
                                <input type="file" class="form-control" name="images[]" multiple/>
                            </div>
                        </div>
                        <div class="form-group row mt-2">
                            <div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                    Add
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

shop/resources/views/seller/edit.blade.php
@extends('layouts.app')
@section ('content')

    <div class="col-md-8">


        <div class="card">
            <div class="card-header">Change Category</div> <div class="card-body">
                <form method="POST" action="{{route('product.update',$data->id)}} " enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label text-md-right"> Name</label>
                        <div class="col-md-6"><input id="name" type="text" name="name" value="{{$data->name}}" required="required" autofocus="autofocus" class="form-control"></div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6"><textarea id="password"  name="description" class="form-control">{{$data->description}}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Cost</label>
                        <div class="col-md-6">
                            <input type="number" class="form-control" name="cost" value="{{$data->cost}}"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="text" class="col-md-4 col-form-label text-md-right">Image</label>
                        <div class="col-md-6">
                            <input type="file" class="form-control" name="images[]" multiple/>
                        </div>
                    </div>
                    <div class="form-group row mt-2"><div class="col-md-8 offset-md-4"><button type="submit" class="btn btn-primary">
                                Change
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

shop/resources/views/seller/images.blade.php
@extends('layouts.app')
@section('content')

    <div class="row mt-4 bg-dark">
        @if($images)
            @foreach($images->get() as $image)
                <div class="col-4  bg-secondary"  data-id="{{$image->id}}">
                    <button type="button" class="close" aria-label="Close">
                        <a href="{{route('img.destroy',['product'=>$image->Product->id,'img'=> $image->id])}}" aria-hidden="true" data-method="delete" class="jquery-postback">&times;</a>
                    </button>
                    <div class="mt-3">
                        <a href="{{route('make_header' ,['product'=>$image->product->id ,'image'=>$image->id])}}">
                            <img src="{{asset('uploads/'.$image->name)}}" alt="" class="img-fluid" >
                        </a>
                    </div>
                </div>
            @endforeach
        @else
            <div class="col-3 ">
                <div class="mt-3 img-open bg-secondary ">

                    <img src="{{asset('uploads/thumb/noimage.jpg')}}" alt="" class="img-fluid" >
                </div>
            </div>
        @endif
    </div>
@endsection

shop/resources/views/seller/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="alert text-center alert-info">
        Welcome Seller page {{auth()->user()->name}}:
    </div>
@endsection

shop/resources/views/seller/orders.blade.php
@extends('layouts.app')
<style>
    img.img-fluid {
        display: inline-block;
        height:60px ;
        width:auto ;
    }
</style>
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Cost</th>
                        <th>Count</th>
                        <th>All Price</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(auth()->user()->products()->get() as $myprod)
                        @foreach($myprod->orders()->get() as $item )
                            <tr data-id="{{$item->id}}">
                                <td>{{ $item->product->name}} </td>
                                <td>{{ $item->product->description }}</td>
                                <td>{{ $item->product->cost }}</td>
                                <td>{{ $item->count }}</td>
                                <td>{{ $item->count * $item->product->cost }}</td>
                                <td><img src="{{asset('uploads\thumb\\'.$item->product->img )}}" class="img-fluid"  alt=""/></td>

                                <td>
                                    <form method ='POST' action="{{route('order.confirm')}}" class="d-inline-block" >
                                        <input type="hidden" name="id" value="{{$item->id}}" />
                                        @method('PUT')
                                        @csrf
                                        <button class="btn btn-primary" type ='submit'> Confirm </button>
                                    </form>
                                </td>
                                <td>
                                    <a href="{{route('myorder.delete',['destroy'=>$item->id ])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                                </td>
                            </tr>
                        @endforeach
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

shop/resources/views/seller/product.blade.php
@extends('layouts.app')
<style>
    img.img-fluid {
        display: inline-block;
        height:60px ;
        width:auto ;
    }
</style>
@section('content')
    <div class="container">
        <h3 class="text-center">Products</h3>
        <a href="{{route('product.create')}}" class="btn btn-info">Add </a>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table mt-3 jquery_table"  >
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Cost</th>
                        <th>Image</th>
                        <th>Listing</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach(auth()->user()->products()->get() as $item)
                        <tr data-id="{{$item->id}}">
                            <td>{{ $item->name}} </td>
                            <td>{{ $item->description }}</td>
                            <td>{{ $item->cost }}</td>
                            <td><a href="{{route('product.show',['id'=>$item->id])}}" class=""><img src="{{asset('uploads\thumb\\'.$item->img )}}" class="img-fluid"  alt=""/></a></td>
                            <td>
                                <form method ='GET' action="{{route('product.edit',['id'=>$item->id])}}" class="d-inline-block" >
                                    @csrf
                                    <button class="btn btn-info" type ='submit'> Edit</button> </form>
                            </td>
                            <td>
                                <a href="{{route('product.destroy',['id'=>$item->id])}}" class="jquery-postback btn  btn-info" data-method ='delete' onclick="return confirm('Are you sure you want to delete this item?')" > Delete </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection